# Generated by Django 4.2.7 on 2023-11-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(verbose_name="is_staff"),
        ),
    ]
