# Generated by Django 4.2.7 on 2023-11-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("excursion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursion",
            name="maximum_user",
            field=models.IntegerField(default=10, verbose_name="maximum_user"),
        ),
        migrations.AddField(
            model_name="excursion",
            name="minimum_user",
            field=models.IntegerField(default=0, verbose_name="minimum_user"),
        ),
        migrations.AddField(
            model_name="excursion",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AddField(
            model_name="excursion",
            name="start_time",
            field=models.DateTimeField(default=None, verbose_name="partenza"),
        ),
        migrations.AddField(
            model_name="excursion",
            name="time_excursion",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="durata"
            ),
        ),
    ]
