# Generated by Django 4.2.7 on 2023-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("excursion", "0003_excursion_end_booking_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursion",
            name="meeting_place",
            field=models.CharField(
                default="", max_length=500, verbose_name="meeting_place"
            ),
        ),
    ]
