# Generated by Django 4.2.7 on 2023-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("excursion", "0004_excursion_meeting_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excursion",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="excursion",
            name="start_time_excursion",
            field=models.DateTimeField(default=None, verbose_name="partenza"),
        ),
    ]
