# Generated by Django 4.2.7 on 2023-11-07 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("excursion", "0005_remove_excursion_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excursion",
            name="date_published",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date_published"
            ),
        ),
        migrations.AlterField(
            model_name="excursion",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="excursion",
            name="start_time_excursion",
            field=models.DateTimeField(
                default=None, verbose_name="start_time_excursion"
            ),
        ),
        migrations.AlterField(
            model_name="excursion",
            name="time_excursion",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="time_excursion"
            ),
        ),
    ]
